# Generated by Django 3.0.3 on 2020-02-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
    ]
