# Generated by Django 3.0.3 on 2020-02-19 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
