# Generated by Django 3.0.3 on 2020-02-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent_tweet',
            field=models.IntegerField(null=True),
        ),
    ]
