# Generated by Django 3.0.3 on 2020-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default="I haven't written a bio yet!", max_length=300),
        ),
    ]
