# Generated by Django 3.0.3 on 2020-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200306_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='green_square.jpg', max_length=140),
        ),
    ]
