# Generated by Django 3.0.3 on 2020-04-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Nowhere', max_length=60),
        ),
    ]
