# Generated by Django 3.0.3 on 2020-05-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='replies',
            field=models.IntegerField(default=0),
        ),
    ]
