# Generated by Django 3.0.3 on 2020-05-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_tweet_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='deleted_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
