# Generated by Django 3.0.3 on 2020-05-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_tweet_deleted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
