# Generated by Django 3.0.3 on 2020-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_favtweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_tweets',
            field=models.ManyToManyField(to='app1.Tweet'),
        ),
        migrations.DeleteModel(
            name='FavTweet',
        ),
    ]
