# Generated by Django 3.0.3 on 2020-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='app1.Profile'),
        ),
    ]
