# Generated by Django 3.0.3 on 2020-05-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_tweets',
            field=models.ManyToManyField(related_name='liked_by', to='app1.Tweet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_tweets',
            field=models.ManyToManyField(related_name='bookmarked_by', to='app1.Tweet'),
        ),
    ]
