# Generated by Django 3.0.3 on 2020-05-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20200521_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='retweets',
            field=models.ManyToManyField(related_name='retweeted_by', to='app1.Tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='parent_tweet_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Tweet'),
        ),
    ]
